services:
  discord-qnap-bot:
    build: .
    container_name: container_name
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./data:/app/data
